addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"         % "0.1.6")
addSbtPlugin("io.spray"                  % "sbt-revolver"         % "0.9.1")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"         % "2.0.0")
addSbtPlugin("net.virtual-void"          % "sbt-dependency-graph" % "0.9.2")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager"  % "1.5.2")
